
spring.application.name=ORDER-SERVICE

server.port=8083

# Database config

spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb
eureka.client.enabled=false
spring.datasource.username=postgres

spring.datasource.password=Dgliger@123!

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Eureka

eureka.client.service-url.defaultZone=http://localhost:8762/eureka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer