spring.application.name=PRODUCT-SERVICE

server.port=8081


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/product_service_db
spring.datasource.username=postgres
spring.datasource.password=Dgliger@123!

spring.datasource.driver-class-name=org.postgresql.Driver


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8762/eureka
