# PORT
server.port=8085

# SERVICE NAME
spring.application.name=cart-service


# POSTGRES DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/cart_db
spring.datasource.username=postgres
spring.datasource.password=Dgliger@123!

spring.datasource.driver-class-name=org.postgresql.Driver


# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



# EUREKA CONFIG
eureka.client.service-url.defaultZone=http://localhost:8762/eureka


